/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cloud_logic_custom": [
        {
            "name": "rateMyMealAPI",
            "endpoint": "https://lnpqigccu4.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "rateMyMealDB-dev",
            "region": "us-west-2"
        }
    ],
    "aws_user_files_s3_bucket": "ratemymeals3bucket101322-dev",
    "aws_user_files_s3_bucket_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:983510c9-415a-41ac-90cb-08e8ff5b4562",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_SW1hV0yGj",
    "aws_user_pools_web_client_id": "4p2a6do2domb7kcv3plk15onrt",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
